### ISSUE TITLE
where do I get champion_keys file?

### ISSUE THREAD

**Issue by hrkamiza** [i32ropie/lol#5]
Hello, I´ve been trying so setup the bot but get the missing file:
[+] Cargando plugins...
Traceback (most recent call last):
  File "./LCS_bot.py", line 11, in <module>
    from config import *
  File "/lol/config.py", line 161, in <module>
    with open('champs_keys.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'champs_keys.json'

**Comment by i32ropie** [comment]
Hi, I just updated the code so you can update that file too with the command `/update_champs_keys` and I also added the file I'm currently using to the main project. I also added all the other champs dbs I use so feel free to use it ^^

If you have any other issue you can ask it :smile:

P.S.: They README.md file is pretty outdated because I have been all the summer studying xD I'll try to update it some day
